In [1]:
print("hello world")

hello world


cold 状态写代码
markdown 写文本
raw NB  原生输入状态

In [2]:
1+5

6

# 大标题

## 二级标题

### 三级标题

选中单元格 按 B 可以新增一行code

选中单元格 按 M 可以将这行编程markdown

按 ctrl+enter 快捷运行

# 单元格的操作

向上新增一个单元格 A

向下新增一个单元格 B

复制单元格 C 粘贴单元格V

Z 撤销

自动补齐 TAB

帮助文档 

len？

help(len)

## 魔法指令

可以对所有常用的指令进行封包
方便之后调用

%run XX.py

%time 记录一行的运行时间

%%time 记录多行的运行时间

%who 找出所有的变量

%whos 找出所有的变量和变量类型

索引

in[45]

out[53]

# Numpy

## numpy 属性

ndim 维度

shape 形状

size 总长度

dtype 元素类别

## 创建numpy 

#### 一维数组

In [5]:
import numpy as np

In [12]:
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [14]:
#查看类型
type(arr1)

numpy.ndarray

In [15]:
#查看维度--一维
arr1.ndim

1

In [16]:
#查看形状
arr1.shape

(9,)

In [17]:
#查看元素数量
arr1.size

9

#### 二维数组

In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr2.ndim

2

In [23]:
arr2.size

6

In [24]:
arr2.shape

(2, 3)

In [25]:
arr2.ndim , arr2.size ,arr2.shape

(2, 6, (2, 3))

### 使用np 的routines 构建矩阵

In [27]:
np.ones(shape=(2,3))

#shape 用元组表示

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones(shape=(1,3))

array([[1., 1., 1.]])

In [30]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones(shape=(3,))

array([1., 1., 1.])

In [32]:
np.ones(shape=(2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

np.zero(shape,dtype=float) 填充0

np.full(shape,fill_value,dtype=float) 随意指定特定数填充

np.eye(N,M=None,K=0,dtype=float) 单位矩阵

In [35]:
#生成等差数列
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
np.linspace(0,100,10,endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [41]:
np.linspace(0,360,4,endpoint=False)

array([  0.,  90., 180., 270.])

In [43]:
# arange 函数  起点，终点，指定步长
np.arange(0,100,step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
np.random.randint(low=0,high=100,size=(3,5))

array([[25, 22, 26, 46,  0],
       [24, 22, 91, 28, 35],
       [74,  5, 13, 46,  3]])

In [45]:
#正态分布函数 期望值175，方差10的10个人的身高
np.random.normal(loc=175,scale=10,size=(10,))

array([164.40467128, 172.77589632, 158.4398003 , 197.77086798,
       174.03675395, 168.01545976, 181.50815848, 180.08134826,
       166.64791282, 180.40114557])

In [46]:
#标准正态分布
np.random.randn(10)

array([ 1.5056303 ,  1.81923396, -1.55189985, -0.95020718,  0.08943995,
       -0.62352364,  0.17083163, -1.20197385, -0.16836923,  0.23075424])

In [48]:
#生成0-1的随机数，左闭右开
np.random.random(size=None)

0.4262018940793578

In [47]:
#随机索引
np.random.permutation(10)

array([9, 0, 2, 6, 3, 4, 7, 1, 8, 5])

#### 随机种子

In [51]:
np.random.seed(0) #添加一个种子  种子可以锁定随机数，随机数不会随意更改
np.random.randint(0,10,size=5)

array([5, 0, 3, 3, 7])

#### 练习题

1. 创建一组形状为（3，4）的二维数组，取值范围（-5，5）
2. 创建一组等差数列，步长为3，数组长度为5
3. 构造一个3维取值范围为0-1的随机数组，数据类型为np.float64,形状为（100，100，3）
4. 已知Π在numpy 中是一个预制常量，可以使用np.pi访问，计算出将一个圆分成8份的代码

In [52]:
np.random.randint(low=-5,high=5,size=(3,4))

array([[ 4, -2,  0, -3],
       [-1,  2,  1,  3],
       [ 3, -4,  1,  2]])

In [66]:
np.linspace(0,15,5,endpoint=False)

np.arange(0,15,step=3)

array([ 0,  3,  6,  9, 12])

In [71]:
np.random.random(size=(100,100,3)).dtype

dtype('float64')

In [59]:
np.pi

3.141592653589793

In [74]:
np.linspace(0,2*np.pi,8,endpoint=False)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

## ndarray 的读写操作

In [77]:
ll=[1,2,3,4]

In [79]:
ll[0]

1

In [80]:
ll[1]

2

In [81]:
l2=[[1,2,3,4],[4,5,6,7]]

In [82]:
l2[1]

[4, 5, 6, 7]

In [83]:
l2[0]

[1, 2, 3, 4]

In [85]:
l2[0][1]

2

In [95]:
arr1=np.random.randint(0,100,size=(2,3,6))
arr1

array([[[82, 37,  7,  2,  2, 11],
        [98, 83, 40, 18, 65, 84],
        [ 5, 53, 18, 98, 19, 34]],

       [[86, 54, 18,  3,  1, 87],
        [88, 65, 80, 12, 24, 83],
        [82, 49, 66, 33, 11, 84]]])

In [ ]:
### 切片
arr1[0:3]
arr1[2:5]
arr1
arr1[start:end:step]

In [97]:
arr1[0:1]

array([[[82, 37,  7,  2,  2, 11],
        [98, 83, 40, 18, 65, 84],
        [ 5, 53, 18, 98, 19, 34]]])

## 练习
1. 构建一个长度为10的随机数组，进行逆序输出
2. 构建一个形状为（5，4）的二维数组，提取最后两列，使用三种方法
3. 构建一个6行5列的数组，对数组进行行方向的随机排序

In [100]:
data1=np.random.random(size=10)

data1[::-1]

array([0.69817054, 0.02784515, 0.05831378, 0.16071333, 0.46886747,
       0.66854312, 0.78295932, 0.48105766, 0.33598254, 0.47692256])

In [102]:
data2=np.random.randint(0,100,size=(5,4))
data2

array([[89, 44, 13, 82],
       [ 3,  1, 46,  7],
       [64,  3, 84, 28],
       [51, 65, 11, 96],
       [ 5, 24, 16, 41]])

In [104]:
data2[:,[-2,-1]]

array([[13, 82],
       [46,  7],
       [84, 28],
       [11, 96],
       [16, 41]])

### 级联

axis=1 竖着轴

axis=0 横着轴

In [108]:
a1 = np.random.randint(0,10,size=(3,4))
a2 = np.random.randint(10,20,size=(3,4))

In [109]:
a1

array([[8, 5, 6, 6],
       [9, 9, 2, 4],
       [8, 0, 3, 0]])

In [110]:
a2

array([[17, 15, 10, 12],
       [14, 10, 10, 16],
       [10, 12, 12, 12]])

In [112]:
np.concatenate((a1,a2),axis=0) #靠着axis=0进行拼接

array([[ 8,  5,  6,  6],
       [ 9,  9,  2,  4],
       [ 8,  0,  3,  0],
       [17, 15, 10, 12],
       [14, 10, 10, 16],
       [10, 12, 12, 12]])

In [114]:
np.concatenate((a1,a2),axis=1)#靠着axis=1进行拼接

array([[ 8,  5,  6,  6, 17, 15, 10, 12],
       [ 9,  9,  2,  4, 14, 10, 10, 16],
       [ 8,  0,  3,  0, 10, 12, 12, 12]])

### 切分

与级联类似，三个函数完成切分工作

np.split

np.vsplit

np.hsplit

In [122]:
arr=np.random.randint(0,100,size=(5,6))
arr

array([[57, 16, 78, 67, 71, 77],
       [ 0, 79, 34, 37, 21, 97],
       [65,  9,  6, 14, 45,  8],
       [89, 25, 13, 96, 89, 98],
       [12, 12, 89, 59, 17, 98]])

In [132]:
np.split(arr,indices_or_sections=2,axis=1)

[array([[57, 16, 78],
        [ 0, 79, 34],
        [65,  9,  6],
        [89, 25, 13],
        [12, 12, 89]]), array([[67, 71, 77],
        [37, 21, 97],
        [14, 45,  8],
        [96, 89, 98],
        [59, 17, 98]])]

h 横向

v 纵向

### 练习
1. 生成两个形状分别为（4，4）和（8，4）的二维整型，并尝试级联


In [139]:
a1 = np.random.randint(0,10,size=(3,4))
a2 = np.random.randint(10,20,size=(3,4))
display(a1,a2)

array([[5, 5, 5, 0],
       [5, 1, 7, 3],
       [6, 2, 4, 5]])

array([[12, 16, 10, 14],
       [12, 19, 15, 14],
       [18, 18, 17, 19]])

In [140]:
np.concatenate((a1,a2),axis=0)

array([[ 5,  5,  5,  0],
       [ 5,  1,  7,  3],
       [ 6,  2,  4,  5],
       [12, 16, 10, 14],
       [12, 19, 15, 14],
       [18, 18, 17, 19]])

### ndarry 的运算
两个矩阵的运算就是对应两个位置的元素进行运算

In [141]:
a1+a2

array([[17, 21, 15, 14],
       [17, 20, 22, 17],
       [24, 20, 21, 24]])

In [142]:
a1-a2

array([[ -7, -11,  -5, -14],
       [ -7, -18,  -8, -11],
       [-12, -16, -13, -14]])

In [143]:
a1>5

array([[False, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [144]:
a1<5

array([[False, False, False,  True],
       [False,  True, False,  True],
       [False,  True,  True, False]])

### 广播机制

1. a=np.ones((4,1)), b=np.arange(4) 求a+b

In [145]:
a=np.ones((4,1))

In [148]:
b=np.arange(4)

In [149]:
a+b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

2.假设有100个员工考勤需要处理，由于上个月统一调休，所以需要将所有人的总考勤数减一，应该如何操作

In [152]:
data=np.random.randint(20,23,size=100)

In [153]:
data-1

array([19, 21, 21, 21, 20, 21, 20, 20, 19, 20, 21, 21, 20, 20, 20, 20, 20,
       21, 19, 19, 20, 20, 19, 19, 19, 20, 19, 21, 21, 19, 19, 21, 20, 20,
       19, 20, 20, 19, 21, 20, 21, 21, 20, 21, 20, 21, 20, 19, 21, 19, 20,
       20, 20, 21, 21, 19, 19, 20, 20, 21, 21, 20, 19, 20, 21, 19, 19, 21,
       19, 19, 19, 20, 21, 20, 21, 19, 19, 21, 21, 21, 21, 20, 20, 20, 20,
       20, 20, 19, 19, 21, 21, 19, 20, 19, 19, 20, 21, 21, 19, 20])

3.假设员工上班时间表通过np.random.randint(7,10,100)获取，如何快速找到上班不足8小时的员工？

In [155]:
data2=np.random.randint(7,10,100)

In [156]:
data2<8

array([ True, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True,  True, False, False, False,  True,  True,
        True, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False,  True, False, False, False,  True, False,
        True])

### 聚合函数

In [158]:
#求和 np.sum
data=np.random.randint(0,100,size=5)
data

array([45, 39, 74, 72, 73])

In [159]:
data.sum()

303

In [160]:
data.sum()

303

In [164]:
data2=np.random.randint(0,100,size=(2,5))
data2

array([[88, 45, 17, 42, 64],
       [31, 26, 62,  9, 88]])

In [166]:
data2.sum(axis=0)

array([119,  71,  79,  51, 152])

In [167]:
data2.sum(axis=1)

array([256, 216])

空值 np.nan

空值和任意值运算都是nan

In [168]:
np.nansum(data) #可以直接跨过空值计算

497

In [169]:
#最大值和最小值
arr.max()

98

In [170]:
arr.min()

0

In [ ]:
# any()和all()
#一个数组中如果至少存在一个true，则返回true
data.any()
#all 一个数组中，如果全部都是true.all 函数就返回true

### 练习

1.生成一个Python 的成绩列表，假设有100人，满分100分，及格60分，如何计算班级的及格率？

In [176]:
python=np.random.randint(0,100,size=100)

In [177]:
#true =1
# false=0
python>60

array([False, False, False,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True, False, False, False,
       False,  True, False, False,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False, False,  True, False,  True, False,  True,  True,
       False])

In [178]:
sum(python>60)/100

0.43

2.标准化就是将一组数据进行如下规则的转化：减去期望值再除以样本方差，请封装一个函数来实现

In [1]:
def standerd_transform(x):
    return (x-x.mean())/x.std()


3.随机生成一个一维数组，比较其中是否有至少一个数据大于3倍平均值

In [17]:
data=np.random.randn(100)

In [18]:
3*data.mean()

0.15616074413881964

In [21]:
(data>3*data.mean()).any()

True

4.生成1000行3列的一个标准正太分布数组，查询每一列是否大于该列的3倍标准差

In [24]:
data=np.random.randn(1000,3)

In [32]:
(data>3*data.std(axis=0)).any(axis=0)

array([ True,  True,  True])

5.检查两个形状相同的数组数值是完全一致的？

In [33]:
a=np.ones(shape=(4,4))
b=np.ones(shape=(4,4))

In [36]:
(a==b).all()

True

## Numpy 数组操作

In [37]:
import numpy as np

#### 添加元素
通过numpy.append 函数在数组的末尾添加值

注意：

1.插入的维度要保证所有数组的长度是相同的

2.如果没有指定轴，数组会被扁平处理

In [39]:
data=[1,2,3,4]

In [40]:
data.append(5)

In [41]:
data

[1, 2, 3, 4, 5]

In [58]:
arr=np.array(data)

In [59]:
arr

array([[1.],
       [1.],
       [1.],
       [1.]])

In [44]:
arr.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [47]:
np.append(arr,5)

array([1, 2, 3, 4, 5, 5])

In [48]:
arr2=np.random.randint(0,10,size=(4,3))

In [49]:
arr2

array([[8, 4, 2],
       [3, 9, 8],
       [5, 8, 0],
       [4, 0, 6]])

In [53]:
np.append(arr2,[[1,2,3],[3,4,5]],axis=0)

array([[8, 4, 2],
       [3, 9, 8],
       [5, 8, 0],
       [4, 0, 6],
       [1, 2, 3],
       [3, 4, 5]])

In [54]:
data=np.ones(shape=(4,1))

In [55]:
data

array([[1.],
       [1.],
       [1.],
       [1.]])

In [56]:
np.append(arr2,data,axis=1)

array([[8., 4., 2., 1.],
       [3., 9., 8., 1.],
       [5., 8., 0., 1.],
       [4., 0., 6., 1.]])

#### 插入元素

np.insert


In [64]:
data=np.ones(5)

In [65]:
data

array([1., 1., 1., 1., 1.])

In [67]:
np.insert(data,3,5) #在3处插入数字5

array([1., 1., 1., 5., 1., 1.])

In [68]:
arr2

array([[8, 4, 2],
       [3, 9, 8],
       [5, 8, 0],
       [4, 0, 6]])

In [72]:
np.insert(arr2,2,[1,1,1,1]) #未指定轴，扁平化

array([8, 4, 1, 1, 1, 1, 2, 3, 9, 8, 5, 8, 0, 4, 0, 6])

In [74]:
np.insert(arr2,2,[1,1,1],axis=0)#指定轴，在序列2处插入

array([[8, 4, 2],
       [3, 9, 8],
       [1, 1, 1],
       [5, 8, 0],
       [4, 0, 6]])

#### 删除元素
numpy.delete

In [76]:
arr

array([[1.],
       [1.],
       [1.],
       [1.]])

In [78]:
np.delete(arr,1)

array([1., 1., 1.])

In [79]:
arr2

array([[8, 4, 2],
       [3, 9, 8],
       [5, 8, 0],
       [4, 0, 6]])

In [80]:
np.delete(arr,1,axis=0)

array([[1.],
       [1.],
       [1.]])

#### 数组变形 reshape

在不改变数据的条件下，改变形状

numpy.reshape(arr,newshape,order='c')

c-按行

f-按列

A- 按原顺序

K-元素在内存中出现的顺序

#### 数组迭代器

In [81]:
for i in arr:
    print(i)

[1.]
[1.]
[1.]
[1.]


In [83]:
for i in arr2:
    print(i)
    print("----")

[8 4 2]
----
[3 9 8]
----
[5 8 0]
----
[4 0 6]
----


In [84]:
for i in arr2.flat:
    print(i)

8
4
2
3
9
8
5
8
0
4
0
6


### NUMPY 数学函数

### 三角函数
np.sign()
np.cos()
np.tan()
接收的参数是弧度不是角度

In [89]:
np.sign(np.pi)

1.0

### 舍入函数

In [92]:
np.around(np.pi)

3.0

In [95]:
np.around(data,3) #3-保留3位小数

array([1., 1., 1., 1., 1.])

### 算数函数 加减乘除

add()
subtract()
multiply()
divide()

numpy.power() 幂运算，可以做开方运算

numpy.mode() 求余运算

np.log() 自然底数的对数 np.log2()

In [98]:
a1= np.random.randint(0,10,size=5)
a2= np.random.randint(0,10,size=5)

In [100]:
np.add(a1,a2)

array([8, 2, 7, 7, 9])

In [102]:
np.power(2,3) #2 的3次方

8

### numpy 查找和排序

### 查找索引
numpy.argmax()和numpy.argmin()